specVersion: 1.0.0
name: avalanche-subql-starter
version: 0.0.1
runner:
  node:
    name: "@subql/node-avalanche"
    version: ">=0.2.0"
  query:
    name: "@subql/query"
    version: ">=1.2.0"
description: The goal of this quick start guide is to index all Pangolin token Approve logs
repository: "https://github.com/jamesbayly/pangolin-approvals-tutorial"
schema:
  file: ./schema.graphql
network:
  endpoint: "http://avalanche.api.onfinality.io:9650"
  chainId: mainnet
  subnet: C
  dictionary: "https://api.subquery.network/sq/subquery/avalanche-dictionary"
dataSources:
  - kind: avalanche/Runtime
    startBlock: 16993850
    # startBlock: 7689920 # Block when the Pangolin Reward contract was created
    options:
      # Must be a key of assets
      abi: erc20
      ## Pangolin reward contract https://snowtrace.io/token/0x88afdae1a9f58da3e68584421937e5f564a0135b
      address: "0x88afdae1a9f58da3e68584421937e5f564a0135b"
    assets:
      erc20:
        file: "./node_modules/@pangolindex/exchange-contracts/artifacts/contracts/staking-rewards/StakingRewards.sol/StakingRewards.json"
    mapping:
      file: "./dist/index.js"
      handlers:
        - handler: handleLog
          kind: avalanche/LogHandler
          filter:
            ## Follows standard log filters https://docs.ethers.io/v5/concepts/events/
            topics:
              - RewardPaid(address user, uint256 reward)
